clc
N=24;
n=0:N-1;
x=1+sin(n*pi/12+3*pi/8);
figure(1)
stem(n,x,'filled')
title('x[n]')
X=(1/N)*fft(x);
figure(2)
subplot(211),stem(n,real(X),"filled")
subplot(212),stem(n,imag(X),"filled")
figure(3)
subplot(211),stem(n,abs(X),"filled")
subplot(212),stem(n,angle(X),"filled")
x_recon=N*ifft(X);
figure(4)
subplot(211),stem(n,real(x_recon),"filled")
subplot(212),stem(n,imag(x_recon),"filled")
